name= input ("Enter Your Name: ")
age= input ("Entert your age: ")
School= input ("Enter your School: ")
print("-----------------------------------------------------------------------------------------------")
print("Your Name is:",name)
print("Your Age is:",age)
print("Your school name are:",School)